### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by Aryess** [cozy-labs/cozy-dev-docs#16]
Hi, 
On [this page](https://dev.cozy.io/nodeapp.html#interacting-with-the-data-system-basics), there's a reference to [main document types](https://dev.cozy.io/nodeapp.html#main-document-types) which doesn't seems to exist anymore.

**Comment by jsilvestre** [comment]
Thank you for the report. Actually, the link below this one was broken too. Fixed and deployed!

**Comment by Aryess** [comment]
Cool. Hadn't read the next one yet :p
