### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/cozy-dev-docs#18]
Hi,

The "Architecture section" link on https://github.com/cozy/cozy-dev-docs/blob/master/source/index.md#data-oriented is broken. I'm not sure where it should point to though.

Thanks

**Comment by Phyks** [comment]
Actually, I guess it should point to https://github.com/cozy/cozy-dev-docs/blob/master/source/index.md#architecture-and-components. I'll make a PR to fix this.

**Comment by clochix** [comment]
Thanks @Phyks, pinging @jsilvestre ☺
